---
name: Darglint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
        branches: [master, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Run Tests
      run: |
        bash scripts/ci_darglint.sh
