---
name: Pytest

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main, dev]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

        # Used by ci_test.sh
    - name: Install dependencies
      run: |
        python setup.py install
        pip install pytest
        pip install solc-select
    - name: Run Tests
      run: |
        pytest tests/test_metadata.py
